# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false
branches:
  except:
    - fix-docs

matrix:
  fast_finish: true
  include:
  # py37 triggers the static code linters; run it first
  - env: CONDA_ENV=py37
  - env: CONDA_ENV=py36-bare-minimum
  - env: CONDA_ENV=py36-min-all-deps
  - env: CONDA_ENV=py36-min-nep18
  - env: CONDA_ENV=py36
  - env: CONDA_ENV=git-tip
  - env: CONDA_ENV=docs

services:
  - mongodb

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml
  - source activate test_env
  # Faithfully reproduce readthedocs CI environment
  - if [[ "$CONDA_ENV" == "docs" ]]; then
    conda install -y -q -c pkgs/main mock pillow sphinx sphinx_rtd_theme; fi
  - conda list
  - pip install --no-deps -e .

script:
  - python -c "import xarray_mongodb"
  - if [[ "$CONDA_ENV" == "py37" ]]; then black -t py36 --check; fi
  - if [[ "$CONDA_ENV" == "py37" ]]; then flake8; fi
  - if [[ "$CONDA_ENV" == "py37" ]]; then mypy .; fi
  - if [[ "$CONDA_ENV" == "docs" ]]; then
    sphinx-build -n -j auto -b html -d build/doctrees doc build/html; fi
  - if [[ "$CONDA_ENV" != "docs" ]]; then
    py.test xarray_mongodb --cov=xarray_mongodb --cov-config ci/.coveragerc --cov-report term-missing; fi
